CREATE TABLE BOOKMARK (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL, URL TEXT NOT NULL, DEL_YN TEXT NOT NULL DEFAULT 'N');

INSERT INTO BOOKMARK(NAME, URL) VALUES ('google', 'https://google.com');
INSERT INTO BOOKMARK(NAME, URL) VALUES ('github', 'https://github.com');
INSERT INTO BOOKMARK(NAME, URL) VALUES ('youtube', 'https://youtube.com');

SELECT * FROM BOOKMARK WHERE DEL_YN = 'N';